
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: minha_api_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: springboot_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # e força a API a procurar o banco pelo nome do container "db" e porta "5432"
      DB_URL: jdbc:postgresql://db:5432/minha_api_db
      DB_USERNAME: api_user
      # Estas variáveis vão puxar os valores do arquivo .env da máquina de quem estiver rodando
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data: