# TODO: Configurar a URL do banco de dados (ex: spring.datasource.url)
# TODO: Configurar o usuário do banco (ex: spring.datasource.username)
# TODO: Configurar a senha do banco (ex: spring.datasource.password)
# TODO: Configurar o dialeto do JPA (ex: spring.jpa.properties.hibernate.dialect)
# TODO: Configurar a porta do servidor (ex: server.port=8080)

# Configurações de conexão com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/minha_api_db

spring.datasource.username=api_user
spring.datasource.password=senha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true